config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("etat_civil.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("django-rq/", include("django_rq.urls")),
    path("deeds/", include("etat_civil.deeds.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

etat_civil/deeds/urls.py
from django.urls import path

from etat_civil.deeds.views import (
    geojson_view,
    flowmap_flows_view,
    flowmap_locations_view,
)

app_name = "deeds"

urlpatterns = [
    path("flowmap/flows/", view=flowmap_flows_view, name="flowmap_flows"),
    path("flowmap/locations/", view=flowmap_locations_view, name="flowmap_locations"),
    path("geojson/", view=geojson_view, name="geojson"),
]

etat_civil/users/urls.py
from django.urls import path

from etat_civil.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

etat_civil/deeds/models.py
from collections import Counter
from datetime import datetime, timedelta

import pandas as pd
from django.core.validators import FileExtensionValidator
from django.db import models
from django.utils.translation import gettext as _
from etat_civil.geonames_place.models import Place
from model_utils.models import TimeStampedModel


class BaseAL(TimeStampedModel):
    title = models.CharField(max_length=128, unique=True)

    class Meta:
        abstract = True
        ordering = ["title"]

    def __str__(self):
        return self.title


class Data(TimeStampedModel):
    title = models.CharField(max_length=64, unique=True)
    data = models.FileField(
        upload_to="uploads/data/",
        validators=[FileExtensionValidator(allowed_extensions=["xlsx"])],
    )

    locations_df = None

    class Meta:
        verbose_name_plural = "Data"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.locations_df = self.get_data_sheet("locations").set_index("display_name")
        super().save(*args, **kwargs)

    def load_data(self, delete=False):
        if not self.data:
            return False

        if self.delete:
            self.sources.all().delete()

        births_df = self.get_data_sheet("births")
        self.load_births(births_df)

        marriages_df = self.get_data_sheet("marriages")
        self.load_marriages(marriages_df)

        deaths_df = self.get_data_sheet("deaths")
        self.load_deaths(deaths_df)

        return True

    def get_data_sheet(self, sheet_name):
        if not sheet_name:
            return None

        df = pd.read_excel(self.data, engine="openpyxl", sheet_name=sheet_name)
        df = df.dropna(how="all")

        df = self.convert_date_columns(df)

        return df

    def convert_date_columns(self, df):
        if df is None:
            return None

        date_columns = filter(lambda x: "date" in x, df.columns)
        for c in date_columns:
            df[c] = pd.to_datetime(df[c], errors="ignore")

        return df

    def load_births(self, births_df):
        return self.load_deed(births_df, Deed.load_birth_deed)

    def load_deed(self, df, load_func):
        if df is None:
            return False

        for index, row in df.iterrows():
            try:
                source = Source.load_source(
                    self, row["classmark"], row["classmark_microfilm"]
                )
                if source:
                    load_func(self, source, row)
            except Exception as e:  # noqa
                print(load_func, index, e)
                continue

        return True

    def load_marriages(self, marriages_df):
        return self.load_deed(marriages_df, Deed.load_marriage_deed)

    def load_deaths(self, deaths_df):
        return self.load_deed(deaths_df, Deed.load_death_deed)

    def get_place(self, name):
        """Returns a geonames place and a return code, and updates the internal
        place name cache, `locations_df`, when new places get a `geonames_id`.
        Code 0, the place was found in the location cache; code 1, the place was
        searched in geonames by geonames id; code 2, the place was searched in
        geonames by name; code 3, the place was searched in geonames by lat, lon;
        code -1, the place was not in the cache and was searched in geonames by
        name."""
        if not name:
            return None, -1

        code = 0
        name = name.strip()
        address = name

        try:
            location = self.locations_df.loc[name]
            address = location["location"].strip()
            geonames_id = location["geonames_id"]

            if pd.notnull(geonames_id):
                # get place by geonames id
                place, created = Place.objects.get_or_create(
                    geonames_id=int(geonames_id)
                )
                if created:
                    code = 1
            elif pd.notnull(location["lat"]) and pd.notnull(location["lon"]):
                # get place by lat, lon
                lat = location["lat"]
                lon = location["lon"]
                geonames_id = f"-{int(lat*10000)}{int(lon*10000)}"
                place, created = Place.objects.get_or_create(
                    geonames_id=int(geonames_id),
                    update_from_geonames=False,
                    lat=location["lat"],
                    lon=location["lon"],
                )
                if created:
                    code = 3
                    place.address = address
                    place.save()
            else:
                # get place by name
                place = Place.get_or_create_from_geonames(address=address)
                code = 2
        except KeyError:
            code = -1

            new_location_df = pd.DataFrame(
                [[name, name]], columns=["display_name", "location"], index=[name]
            )
            self.locations_df = self.locations_df.append(new_location_df, sort=True)
            self.locations_df.set_index("display_name")

            # get place by name
            place = Place.get_or_create_from_geonames(address=name)

        # updates the locations cache
        if place:
            self.locations_df.loc[name, "geonames_id"] = place.geonames_id

            place.address = address
            place.update_from_geonames = False
            place.save()

        return place, code


class Source(TimeStampedModel):
    data = models.ForeignKey(Data, on_delete=models.CASCADE, related_name="sources")
    classmark = models.CharField(max_length=32)
    microfilm = models.CharField(max_length=32)

    class Meta:
        unique_together = ["data", "classmark", "microfilm"]

    def __str__(self):
        return "{}: {}".format(self.classmark, self.microfilm)

    @staticmethod
    def load_source(data, classmark, microfilm):
        if pd.notnull(classmark):
            classmark = classmark.strip()
        else:
            return None

        if pd.notnull(microfilm):
            microfilm = microfilm.strip()
        else:
            return None

        source, _ = Source.objects.get_or_create(
            data=data, classmark=classmark, microfilm=microfilm
        )

        return source


class DeedType(BaseAL):
    @staticmethod
    def get_birth():
        return DeedType.objects.get(title="birth")

    @staticmethod
    def get_death():
        return DeedType.objects.get(title="death")

    @staticmethod
    def get_marriage():
        return DeedType.objects.get(title="marriage")


class Deed(TimeStampedModel):
    deed_type = models.ForeignKey(DeedType, on_delete=models.CASCADE)
    n = models.PositiveSmallIntegerField(blank=True, null=True)
    date = models.DateField(help_text=_("Date of the deed record"))
    place = models.ForeignKey(
        Place,
        on_delete=models.CASCADE,
        related_name="deeds",
        help_text=_("Place of the deed record"),
    )
    source = models.ForeignKey(Source, on_delete=models.CASCADE)
    parties = models.ManyToManyField(
        "Person", through="Party", through_fields=("deed", "person")
    )
    notes = models.TextField(blank=True, null=True)

    class Meta:
        unique_together = ["n", "date", "place"]

    def __str__(self):
        return "{}: {} - {}; {}".format(self.deed_type, self.n, self.date, self.place)

    @property
    def is_birth(self):
        return self.deed_type == DeedType.get_birth()

    @property
    def is_birth_legitimate(self):
        return self.is_birth and "legitimate birth: true" in self.notes.lower()

    @staticmethod
    def load_birth_deed(data, source, row):
        if data is None or source is None or row is None:
            return None

        deed_type = DeedType.get_birth()
        deed_n = Deed.get_deed_n(row)
        deed_date = Deed.get_deed_date(row)
        deed_place, _ = data.get_place(row["deed_location"])
        deed_notes = Deed.get_deed_notes(row)

        deed, _ = Deed.objects.get_or_create(
            deed_type=deed_type,
            n=deed_n,
            date=deed_date,
            place=deed_place,
            source=source,
            notes=deed_notes,
        )

        Person.load_father(data, deed, row)
        Person.load_mother(data, deed, row)

        return deed

    @staticmethod
    def get_deed_n(row):
        if row is None:
            return -1

        try:
            return int(row["deed_number"])
        except (KeyError, ValueError):
            return 0

    @staticmethod
    def get_deed_date(row):
        if row is None or "deed_date" not in row:
            return None

        deed_date = row["deed_date"]

        if isinstance(deed_date, str):
            deed_date = pd.to_datetime(deed_date).date()

        return deed_date

    @staticmethod
    def get_deed_notes(row):
        if row is None:
            return None

        notes = row["comments"]

        try:
            notes = f'Legitimate birth: {row["birth_legitimate"]}; {notes}'
            notes = notes.strip()
        except KeyError:
            pass

        return notes

    @staticmethod
    def load_marriage_deed(data, source, row):
        if data is None or source is None or row is None:
            return None

        deed_type = DeedType.get_marriage()
        deed_n = Deed.get_deed_n(row)
        deed_date = Deed.get_deed_date(row)
        deed_place, _ = data.get_place(row["deed_location"])
        deed_notes = Deed.get_deed_notes(row)

        deed, _ = Deed.objects.get_or_create(
            deed_type=deed_type,
            n=deed_n,
            date=deed_date,
            place=deed_place,
            source=source,
            notes=deed_notes,
        )

        Person.load_groom(data, deed, row)
        Person.load_bride(data, deed, row)

        return deed

    @staticmethod
    def load_death_deed(data, source, row):
        if data is None or source is None or row is None:
            return None

etat_civil/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

etat_civil/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

etat_civil/deeds/views.py
import csv
from django.http import HttpResponse, JsonResponse
from django.views import View
from etat_civil.deeds.models import Person
from etat_civil.geonames_place.models import Place


class GeoJSONView(View):
    http_method_names = ["get"]

    def get(self, request, *args, **kwargs):
        response = JsonResponse(Person.persons_to_geojson())
        response["Content-Disposition"] = 'attachment; filename="geojson.json"'

        return response


geojson_view = GeoJSONView.as_view()


class FlowmapLocationsView(View):
    http_method_names = ["get"]

    def get(self, request, *args, **kwargs):
        response = HttpResponse(content_type="text/tsv")
        response["Content-Disposition"] = 'attachment; filename="locations.tsv"'

        csv_writer = csv.writer(response, delimiter="\t", quoting=csv.QUOTE_NONNUMERIC)
        csv_writer.writerow(["id", "name", "lat", "lon"])
        csv_writer.writerows(Place.places_to_list())

        return response


flowmap_locations_view = FlowmapLocationsView.as_view()


class FlowmapFlowsView(View):
    http_method_names = ["get"]

    def get(self, request, *args, **kwargs):
        response = HttpResponse(content_type="text/tsv")
        response["Content-Disposition"] = 'attachment; filename="flows.tsv"'

        csv_writer = csv.writer(response, delimiter="\t", quoting=csv.QUOTE_NONNUMERIC)
        csv_writer.writerow(["origin", "dest", "count"])
        csv_writer.writerows(Person.persons_to_flows())

        return response


flowmap_flows_view = FlowmapFlowsView.as_view()

etat_civil/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, RedirectView, UpdateView
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

etat_civil/templates/base.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}État Civil{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}

    <!-- Latest compiled and minified Bootstrap CSS -->
    <link
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous">


    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- This file stores project-specific CSS -->

    <link href="{% static 'css/project.css' %}" rel="stylesheet">


    {% endblock %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button"
          data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false"
          aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">État Civil</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span
                  class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="databaseDropdown"
                role="button" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false">
                Database
              </a>
              <div class="dropdown-menu" aria-labelledby="databaseDropdown">
                <a class="dropdown-item"
                  href="{% url 'admin:index' %}">Admin</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item"
                  href="{% url 'admin:app_list' 'deeds' %}">Deeds</a>
                <a class="dropdown-item"
                  href="{% url 'admin:app_list' 'geonames_place' %}">Places</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="exploreDropdown"
                role="button" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false">
                Export
              </a>
              <div class="dropdown-menu" aria-labelledby="exploreDropdown">
                <a class="dropdown-item"
                  href="{% url 'deeds:geojson' %}">GeoJSON</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item"
                  href="{% url 'deeds:flowmap_locations' %}">flowmap.blue:
                  locations</a>
                <a class="dropdown-item"
                  href="{% url 'deeds:flowmap_flows' %}">flowmap.blue: flows</a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="exploreDropdown"
                role="button" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false">
                Explore
              </a>
              <div class="dropdown-menu" aria-labelledby="exploreDropdown">
                <a class="dropdown-item" href="http://localhost:3000/"
                  target="metabase">Metabase</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item"
                  href="https://flowmap.blue/1hsU13EUFyX8m9xp7GYGGEMyC1bZ8_9sU6b4e2KHwVSc"
                  target="flowmap">flowmap.blue</a>
                <a class="dropdown-item" href="https://kepler.gl/"
                  target="kepler">kepler.gl</a>
              </div>
            </li>
          </ul>
          <ul class="navbar-nav">
            {% if request.user.is_authenticated %}
            <li class="nav-item align-right">
              {# URL provided by django-allauth/account/urls.py #}
              <a class="nav-link"
                href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
            </li>
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a class="nav-link"
                href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
            </li>
            {% else %}
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a id="sign-up-link" class="nav-link"
                href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
            </li>
            <li class="nav-item">
              {# URL provided by django-allauth/account/urls.py #}
              <a id="log-in-link" class="nav-link"
                href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
      {% for message in messages %}
      <div
        class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
        {{ message }}<button type="button" class="close" data-dismiss="alert"
          aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      {% endfor %}
      {% endif %}

      {% block content %}
      <p>Welcome to the État Civil project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}

    <!-- Bootstrap JS and its dependencies-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
      integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
      crossorigin="anonymous"></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"></script>

    <!-- Your stuff: Third-party javascript libraries go here -->


    <!-- place project specific Javascript in this file -->

    <script src="{% static 'js/project.js' %}"></script>


    {% endblock javascript %}
  </body>

</html>